name: Python Tests

on:
  push:
    branches:
      - main  # Runs on every push to the "main" branch
  pull_request:
    branches:
      - main  # Runs on pull requests to the "main" branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specifies that the job should run on an Ubuntu machine

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # This action checks out the repository code to the workflow

    - name: Set up Python
      uses: actions/setup-python@v2  # This action sets up Python on the runner
      with:
        python-version: '3.9'  # Replace this with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrades pip
        pip install -r requirements.txt  # Installs dependencies from requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Runs the tests and stops after 1 failure
